/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author LucasMiranda
 */
public class AgregarPregunta extends javax.swing.JFrame {

    int id_cuest = 0;
    int id_pregunta;
    ArrayList<String> arrayOpciones = new ArrayList<String>();
    ArrayList<Integer> arrayIdOpciones = new ArrayList<Integer>();
    int cant_preguntas = 0;
    int tipo = 1;
    
    /**
     * Creates new form AgregarPregunta
     */
    public AgregarPregunta() {
        initComponents();
        buttonGroup1.add(jRadioButtonAbierta);
        buttonGroup1.add(jRadioButtonMultipleOp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txt_pregunta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_respuesta = new javax.swing.JTextField();
        lista_opciones = new java.awt.List();
        jRadioButtonAbierta = new javax.swing.JRadioButton();
        jRadioButtonMultipleOp = new javax.swing.JRadioButton();
        varable = new javax.swing.JLabel();
        preguntas = new javax.swing.JLabel();
        buttonAgregarOpcion = new javax.swing.JButton();
        agregarPregunta = new javax.swing.JButton();
        button2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar Pregunta");

        txt_pregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_preguntaActionPerformed(evt);
            }
        });

        jLabel1.setText("Pregunta");

        jLabel2.setText("Respuesta");

        txt_respuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_respuestaActionPerformed(evt);
            }
        });

        jRadioButtonAbierta.setText("Pregunta Abierta");
        jRadioButtonAbierta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAbiertaActionPerformed(evt);
            }
        });

        jRadioButtonMultipleOp.setSelected(true);
        jRadioButtonMultipleOp.setText("Multiple Opcion");
        jRadioButtonMultipleOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMultipleOpActionPerformed(evt);
            }
        });

        varable.setText("Preguntas agregadas: ");

        preguntas.setText("0");

        buttonAgregarOpcion.setText("Agregar Opcion  >>");
        buttonAgregarOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarOpcionActionPerformed(evt);
            }
        });

        agregarPregunta.setText("Agregar Pregunta >>");
        agregarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPreguntaActionPerformed(evt);
            }
        });

        button2.setText("Finalizar Cuestionario");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_pregunta))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonMultipleOp)
                                            .addComponent(jRadioButtonAbierta)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(varable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(preguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonAgregarOpcion)
                                .addGap(29, 29, 29)))
                        .addComponent(lista_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(agregarPregunta)
                        .addGap(34, 34, 34)
                        .addComponent(button2)
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lista_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jRadioButtonMultipleOp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonAbierta)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buttonAgregarOpcion)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(varable)
                            .addComponent(preguntas))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(agregarPregunta)))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_preguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_preguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_preguntaActionPerformed

    private void txt_respuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_respuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_respuestaActionPerformed

    private void jRadioButtonAbiertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAbiertaActionPerformed
        if (jRadioButtonAbierta.isSelected()==true){
            txt_respuesta.setEnabled(false);
            buttonAgregarOpcion.setEnabled(false);
            tipo=0;
        }    
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAbiertaActionPerformed

    private void jRadioButtonMultipleOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMultipleOpActionPerformed
        if (jRadioButtonAbierta.isSelected()==false){
            txt_respuesta.setEnabled(true);
            buttonAgregarOpcion.setEnabled(true);
            tipo=1;
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMultipleOpActionPerformed

    private void buttonAgregarOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarOpcionActionPerformed
        // TODO add your handling code here:
         if (txt_respuesta.getText().equals("")){
            JOptionPane.showMessageDialog(null,"El campo Respuesta no puede estar vacío!");
        } else {
        int id_val_op = agregarValorOpcion(txt_respuesta.getText());
        arrayIdOpciones.add(id_val_op);
        System.out.println("id opciones "+arrayIdOpciones);
        lista_opciones.add(txt_respuesta.getText());
        arrayOpciones.add(txt_respuesta.getText());
        txt_respuesta.setText("");
        System.out.println(arrayOpciones);
        }
    }//GEN-LAST:event_buttonAgregarOpcionActionPerformed

    private void agregarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPreguntaActionPerformed
        // TODO add your handling code here:
          if (txt_pregunta.getText().equals("")){
            JOptionPane.showMessageDialog(null,"El campo Pregunta no puede estar vacío!");
        } else{
            //crear opcion
            int id_opc = setOpcion(txt_pregunta.getText());
            System.out.println("opcion "+id_opc);
            //relacionar opcion con valores
            for (int i=0; i<arrayOpciones.size(); i++){
                System.out.println("asociando opcion "+id_opc+" con valor "+arrayIdOpciones.get(i));
                asociarOpcionesConValores(id_opc, arrayIdOpciones.get(i));
            }
            //crear pregunta
            id_pregunta = agregarPregunta2(txt_pregunta.getText(), tipo, id_opc);
            System.out.println("pregunta id "+id_pregunta);
            //relacionar pregunta con cuestionario
            cant_preguntas++;
            asociarPreguntaConCuestionario(id_pregunta, id_cuest, cant_preguntas);
            
            preguntas.setText(String.valueOf(cant_preguntas));
            
            //limpiar variables
            lista_opciones.removeAll();
            txt_pregunta.setText("");
            txt_respuesta.setText("");
            lista_opciones.removeAll();
            arrayIdOpciones.removeAll(arrayIdOpciones);
            arrayOpciones.removeAll(arrayOpciones);
            System.out.println("el array de los ids opciones es.... "+arrayIdOpciones);
            System.out.println("el array de las opciones es.... "+arrayOpciones);
            this.setAlwaysOnTop(false);
            JOptionPane.showMessageDialog(null,"Pregunta agregada satisfactoriamente!");
        }
    }//GEN-LAST:event_agregarPreguntaActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Cuestionario creado con éxito!");
        this.dispose();
        
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPregunta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPregunta;
    private javax.swing.JButton button2;
    private javax.swing.JButton buttonAgregarOpcion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonAbierta;
    private javax.swing.JRadioButton jRadioButtonMultipleOp;
    private java.awt.List lista_opciones;
    private javax.swing.JLabel preguntas;
    private javax.swing.JTextField txt_pregunta;
    private javax.swing.JTextField txt_respuesta;
    private javax.swing.JLabel varable;
    // End of variables declaration//GEN-END:variables

    private static int agregarValorOpcion(java.lang.String descripcion) {
        _109._2._0._10.server_php.Comision service = new _109._2._0._10.server_php.Comision();
        _109._2._0._10.server_php.ComisionPortType port = service.getComisionPort();
        return port.agregarValorOpcion(descripcion);
    }

    private static int agregarPregunta(java.lang.String descripcion, int tipo) {
        _109._2._0._10.server_php.Comision service = new _109._2._0._10.server_php.Comision();
        _109._2._0._10.server_php.ComisionPortType port = service.getComisionPort();
        return port.agregarPregunta(descripcion, tipo);
    }


    private static int asociarPreguntaConCuestionario(int idPreg, int idCuest, int indice) {
        _109._2._0._10.server_php.Comision service = new _109._2._0._10.server_php.Comision();
        _109._2._0._10.server_php.ComisionPortType port = service.getComisionPort();
        return port.asociarPreguntaConCuestionario(idPreg, idCuest, indice);
    }

    private static int asociarPreguntaConOpcion(int idPreg, int idOp) {
        _109._2._0._10.server_php.Comision service = new _109._2._0._10.server_php.Comision();
        _109._2._0._10.server_php.ComisionPortType port = service.getComisionPort();
        return port.asociarPreguntaConOpcion(idPreg, idOp);
    }

    private static int setOpcion(java.lang.String descripcion) {
        _109._2._0._10.server_php.Comision service = new _109._2._0._10.server_php.Comision();
        _109._2._0._10.server_php.ComisionPortType port = service.getComisionPort();
        return port.setOpcion(descripcion);
    }

    private static int asociarOpcionesConValores(int idOpc, int valor) {
        _109._2._0._10.server_php.Comision service = new _109._2._0._10.server_php.Comision();
        _109._2._0._10.server_php.ComisionPortType port = service.getComisionPort();
        return port.asociarOpcionesConValores(idOpc, valor);
    }

    private static int agregarPregunta2(java.lang.String descripcion, int tipo, int idOpciones) {
        _109._2._0._10.server_php.Comision service = new _109._2._0._10.server_php.Comision();
        _109._2._0._10.server_php.ComisionPortType port = service.getComisionPort();
        return port.agregarPregunta2(descripcion, tipo, idOpciones);
    }
    
}
