/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import proyecto.clases.Global;
import proyecto.clases.Validador;

/**
 *
 * @author HP
 */
public class AltaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form AltaUsuario
     */
    public AltaUsuario() {
        Image ico = new ImageIcon(Global.directorioLocal + "\\museo.png").getImage();
        setIconImage(ico);
        initComponents();
        this.setLocationRelativeTo(null);
        LimpiarForm();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_ape = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ci = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_nick = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_tipoUs = new javax.swing.JComboBox();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de Usuario");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Alta de Usuario");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");

        txt_nom.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido:");

        txt_ape.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("CI:");

        txt_ci.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_ci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ciActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Email:");

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Nick:");

        txt_nick.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Pass:");

        txt_pass.setEditable(false);
        txt_pass.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(102, 102, 102));
        txt_pass.setText("default");
        txt_pass.setToolTipText("Pass: La contraseña por defecto es \"default\" el usuario debera cambiarla la primera vez que ingrese");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Tipo Usuario:");

        txt_tipoUs.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_tipoUs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Empleado" }));

        Aceptar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Aceptar.setText("Guardar");
        Aceptar.setToolTipText("Registrar los cambios en el sistema");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.setToolTipText("Descartar los cambios y cerrar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(txt_nick)
                            .addComponent(txt_ape, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_email)
                            .addComponent(txt_nom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_ci, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tipoUs, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_ape)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_ci)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_nick)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tipoUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(Aceptar))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(rootPane, "¿Cerrar cuadro de alta?\nSe perderá cualquier cambio no guardado.") == JOptionPane.YES_OPTION){
            LimpiarForm();
            this.dispose();
        }
    }//GEN-LAST:event_CancelarActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:

        Boolean error = false;

        //VALIDACION DE LOS DATOS DEL FORM

        //NOMBRE
        if("".equals(txt_nom.getText())){
            txt_nom.setBackground(Color.pink);
            txt_nom.setToolTipText("Debes completar este campo");
            error = true;
        }else{
            txt_nom.setBackground(Color.white);
            txt_nom.setToolTipText(null);
        }
        //APELLIDO
        if("".equals(txt_ape.getText())){
            txt_ape.setBackground(Color.pink);
            txt_ape.setToolTipText("Debes completar este campo");
            error = true;
        }else{
            txt_ape.setBackground(Color.white);
            txt_ape.setToolTipText(null);
        }
        //CEDULA
        if("".equals(txt_ci.getText())){ //vacio
            txt_ci.setBackground(Color.pink);
            txt_ci.setToolTipText("Debes completar este campo");
            error = true;
        }else if(txt_ci.getText().length() < 8 || txt_ci.getText().length() > 8){ //largo incorrecto
            txt_ci.setBackground(Color.pink);
            txt_ci.setToolTipText("El largo debe ser de 8 cifras, no se admiten puntos ni guiones");
            error = true;
        }else if(!Validador.isNumeric(txt_ci.getText())){ //no numerico
            txt_ci.setBackground(Color.pink);
            txt_ci.setToolTipText("Sólo se admiten números");
            error = true;
        }else{
            int ci = 0;
            ci =  Integer.parseInt(txt_ci.getText());
            int u = 0;
            u = Validador.validarCedula(ci);
            if (u == 1){
                txt_ci.setBackground(Color.white);
                txt_ci.setToolTipText("La CI es válida");}
            else{
                txt_ci.setBackground(Color.pink);
                txt_ci.setToolTipText("La CI no es válida. Verifícala.");
                error = true;
            }
        }
        //EMAIL
        if("".equals(txt_email.getText())){ //vacio
            txt_email.setBackground(Color.pink);
            txt_email.setToolTipText("Debes completar este campo");
            error = true;
        }else if(!Validador.isEmail(txt_email.getText())){ //formato incorrecto
            txt_email.setBackground(Color.pink);
            txt_email.setToolTipText("El formato de email es incorrecto");
            error = true;
        }else{
            txt_email.setBackground(Color.white);
            txt_email.setToolTipText(null);
        }
        //NICK
        if("".equals(txt_nick.getText())){ //vacio
            txt_nick.setBackground(Color.pink);
            txt_nick.setToolTipText("Debes completar este campo");
            error = true;
        }else{
            txt_nick.setBackground(Color.white);
            txt_nick.setToolTipText(null);
        }
        //CONTRASEÑA
        /*if("".equals(txt_pass.getText())){ //vacio
            txt_pass.setBackground(Color.pink);
            txt_pass.setToolTipText("Debes completar este campo");
            error = true;
        }else{
            txt_pass.setBackground(Color.white);
            txt_pass.setToolTipText(null);
        }        */
        //GUARDAR CAMBIOS
        if(error == false){
            int resultado = AltaUs();

            if(resultado == 0){
                if(JOptionPane.showConfirmDialog(this, "Usuario registrado con éxito.\n¿Quieres registrar otro?") == JOptionPane.YES_OPTION){
                    LimpiarForm();
                }else{
                    this.dispose();
                }
            }else{
                JOptionPane.showMessageDialog(this, "El nick ya existe. Por favor intenta con otro.");
                txt_nick.setBackground(Color.pink);
                txt_nick.setToolTipText("El nick ya existe, intenta con otro");
            }
            /* -1 nick ya existe, 0 ok */
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debes corregir los errores para guardar los datos.", "Error en el formulario", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void txt_ciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaUsuario().setVisible(true);
            }
        });
    }
    
    /**
     * Da de alta un nuevo usuario en el sistema.
     * @return 
     */
    public int AltaUs(){
        int tipoUsuario;
        if(txt_tipoUs.getSelectedIndex() == 0){
            tipoUsuario = 1;
        }else{
            tipoUsuario = 2;
        }
        
        int de = altaUsuario(txt_nom.getText(), txt_ape.getText(), txt_ci.getText(),txt_email.getText(),tipoUsuario,txt_nick.getText(), txt_pass.getText());
        //System.out.print(de);
        if(de == -1 ){
            //JOptionPane.showMessageDialog(null,"Nick ya utilizado");
            return -1;
        }else{
            return 0;
        }
    }
    
    /**
     * Limpia los datos ingresados en el form de Alta de Usuario.
     */
    public void LimpiarForm(){
        txt_nom.setText(null);
        txt_nom.setBackground(Color.white);
        txt_nom.setToolTipText(null);
        
        txt_ape.setText(null);
        txt_ape.setBackground(Color.white);
        txt_ape.setToolTipText(null);
        
        txt_ci.setText(null);
        txt_ci.setBackground(Color.white);
        txt_ci.setToolTipText(null);
        
        txt_email.setText(null);
        txt_email.setBackground(Color.white);
        txt_email.setToolTipText(null);
        
        txt_nick.setText(null);
        txt_nick.setBackground(Color.white);
        txt_nick.setToolTipText(null);
        
       /* txt_pass.setText(null);
        txt_pass.setBackground(Color.white);
        txt_pass.setToolTipText(null);
        */
        txt_tipoUs.setSelectedIndex(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_ape;
    private javax.swing.JTextField txt_ci;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nick;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_pass;
    private javax.swing.JComboBox txt_tipoUs;
    // End of variables declaration//GEN-END:variables

    private static int altaUsuario(java.lang.String nombre, java.lang.String apellido, java.lang.String cedula, java.lang.String email, int tipoUs, java.lang.String nick, java.lang.String pass) {
        _109._2._0._10.server_php.Comision service = new _109._2._0._10.server_php.Comision();
        _109._2._0._10.server_php.ComisionPortType port = service.getComisionPort();
        return port.altaUsuario(nombre, apellido, cedula, email, tipoUs, nick, pass);
    }
    /*
    public int validarCedula(int ci){
        //Inicializo los coefcientes en el orden correcto

        String aux = Integer.toString(ci);

        String cis[] = new String[8];    
        String validador[] = new String[7];
        int c = 0;
        int c1 = 0;
        int dveri = 0;

        for(int e = 0; e<8; e++){   
            if(e != 7) {
                cis[e] = aux.substring(e,e+1);
            }else {
                dveri = Integer.parseInt(aux.substring(e,e+1));
            }    
            // System.out.println(cis[e]);
        }

        for (int i = 0 ; i<7 ; i++){
            if(c==0){
            validador[i] = Integer.toString(2);}
            if(c==1){
            validador[i] = Integer.toString(9);}
            if(c==2){
            validador[i] = Integer.toString(8);}  
            if(c==3){
            validador[i] = Integer.toString(7);}
            if(c==4){
            validador[i] = Integer.toString(6);}
            if(c==5){
            validador[i] = Integer.toString(3);}
            if(c==6){
            validador[i] = Integer.toString(4);}
            c++;
        //    System.out.println(validador[i]); 
        }

        int ce = 0;
        int suma = 0;
        int f = 0;
        String multi[] = new String[7];
        for(int y = 0 ; y < 7 ; y++){
            multi[y] = Integer.toString(Integer.parseInt(cis[y]) * Integer.parseInt(validador[y]));
            if(multi[y].length()>1){
            f = Integer.parseInt(multi[y].substring(1, 2));
            suma = suma + f;
            }else{
            f = Integer.parseInt(multi[y]);
            suma = suma + f;
            }  

        }

        if((suma % 10) == 0){
            return 1;
        }else{
            boolean ok = false;
            int resultado = 0;
            int resultado2 = 0;
            int mayor = 0;
            String aux2;
            while(ok == false){
                if(mayor < suma){
                    mayor++;
                }else{
                    aux2 = Integer.toString(mayor);    
                    if(aux2.substring(1, 2).equals("0")){
                        ok = true;
                    }else{
                        mayor++;
                    }
                }
            }
            resultado = mayor - suma;
            resultado2 = 10-(suma %10);

            if(resultado == resultado2 && resultado == dveri) {
                return 1;
            }else {
                return 0;
            }
        }
    }*/
}
