/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import proyecto.clases.Global;

/**
 *
 * @author SysAdmin
 */
public class Passwd extends javax.swing.JFrame {

    /**
     * Creates new form Passwd
     */
    public Passwd() {
        
        initComponents();
        Image ico = new ImageIcon(Global.directorioLocal + "\\museo.png").getImage();
        setIconImage(ico);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pass_txt = new javax.swing.JPasswordField();
        rep_txt = new javax.swing.JPasswordField();
        ok_btn = new javax.swing.JButton();
        can_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cambio de Contraseña");
        setAlwaysOnTop(true);
        setResizable(false);

        pass_txt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        rep_txt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        ok_btn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ok_btn.setText("Guardar");
        ok_btn.setToolTipText("Guardar los cambios");
        ok_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_btnActionPerformed(evt);
            }
        });

        can_btn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        can_btn.setText("Cancelar");
        can_btn.setToolTipText("Descartar los cambios y cerrar ventana");
        can_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                can_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Contraseña nueva: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Repetir contraseña:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Escribe tu contraseña nueva:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rep_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ok_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(can_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rep_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(can_btn)
                    .addComponent(ok_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_btnActionPerformed
        // TODO add your handling code here:
        boolean error = false;
        
        if("".equals(pass_txt.getText())){ //vacio
            pass_txt.setBackground(Color.pink);
            pass_txt.setToolTipText("Debes completar este campo");
            pass_txt.setText("");
            pass_txt.requestFocus();
            error = true;
        }else{
            pass_txt.setBackground(Color.white);
            pass_txt.setToolTipText(null);
        }
        
        if(rep_txt.getText().equals("")){ //vacio
            rep_txt.setBackground(Color.pink);
            rep_txt.setToolTipText("Debes completar este campo");
            rep_txt.setText("");
            rep_txt.requestFocus();
            error = true;
        }else{
            rep_txt.setBackground(Color.white);
            rep_txt.setToolTipText(null);
        }
        
        if(error == false){
            if(pass_txt.getText().equals(rep_txt.getText())){
                if("default".equals(pass_txt.getText())){
                    pass_txt.setBackground(Color.pink);
                    pass_txt.setToolTipText("No puede ser igual a la contraseña por defecto");
                    rep_txt.setBackground(Color.pink);
                    rep_txt.setToolTipText("No puede ser igual a la contraseña por defecto");
                    JOptionPane.showMessageDialog(rootPane, "Los datos no son correctos. Por favor verifícalos.", "Error en formulario", 2);
                }else{
                    if(passwd(Global.nickUsLog, pass_txt.getText()) == 0){
                        pass_txt.setBackground(Color.white);
                        pass_txt.setToolTipText(null);
                        rep_txt.setBackground(Color.white);
                        rep_txt.setToolTipText(null);
                        JOptionPane.showMessageDialog(rootPane, "Su contraseña se modificó correctamente.");
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "No se pudo cambiar la contraseña.\nPor favor inténtalo de nuevo.", "Error", 2);
                    }
                }
            }else{
                pass_txt.setBackground(Color.pink);
                pass_txt.setToolTipText("Las contraseñas son diferentes");
                rep_txt.setBackground(Color.pink);
                rep_txt.setToolTipText("Las contraseñas son diferentes");
                JOptionPane.showMessageDialog(rootPane, "Las contraseñas son diferentes. Verifícalas.", "Error en formulario", 2);
                 rep_txt.setText("");
                 pass_txt.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Los datos no son correctos. Por favor verifícalos.", "Error en formulario", 2);
        }        
    }//GEN-LAST:event_ok_btnActionPerformed

    private void can_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_can_btnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Debes cambiar la contraseña por defecto para iniciar la sesión");
        this.dispose();
    }//GEN-LAST:event_can_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Passwd().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton can_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton ok_btn;
    private javax.swing.JPasswordField pass_txt;
    private javax.swing.JPasswordField rep_txt;
    // End of variables declaration//GEN-END:variables

    private static int passwd(java.lang.String nick, java.lang.String pass) {
        _109._2._0._10.server_php.Comision service = new _109._2._0._10.server_php.Comision();
        _109._2._0._10.server_php.ComisionPortType port = service.getComisionPort();
        return port.passwd(nick, pass);
    }
}
