/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto.clases.Global;
import proyecto.clases.Validador;

/**
 *
 * @author SysAdmin
 */
public class PerfilUsuario extends javax.swing.JFrame {
    private final DefaultTableModel mod;
    int idUsu;
    ProcesandoPeticion prc = new ProcesandoPeticion();
    
    
    /**
     * Creates new form EliminarUsu
     */
    public PerfilUsuario() {
        Image ico = new ImageIcon(Global.directorioLocal + "\\museo.png").getImage();
        setIconImage(ico);
        initComponents();
        prc.setLocationRelativeTo(null);
        prc.setVisible(true);
        this.setLocationRelativeTo(null);
        mod = new DefaultTableModel();
        label_password.setVisible(false);
        check_pass.setSelected(false);
        label_pass1.setEnabled(false);
        label_pass2.setEnabled(false);
        LabPass1.setEnabled(false);
        LabPass2.setEnabled(false);
        label_nombre.setToolTipText(null);
        label_apellido.setToolTipText(null);
        label_cedula.setToolTipText(null);
        label_email.setToolTipText(null);
        label_pass1.setToolTipText(null);
        label_pass2.setToolTipText(null);
        CargarDatosUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_cedula = new javax.swing.JTextField();
        label_email = new javax.swing.JTextField();
        label_nombre = new javax.swing.JTextField();
        label_apellido = new javax.swing.JTextField();
        LabApellido = new javax.swing.JLabel();
        LabNombre = new javax.swing.JLabel();
        LabIdUsu = new javax.swing.JLabel();
        LabNick = new javax.swing.JLabel();
        LabEmail = new javax.swing.JLabel();
        LabCedula = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        label_nick = new javax.swing.JLabel();
        BotGuardar = new javax.swing.JButton();
        BotCancelar = new javax.swing.JButton();
        LabPass1 = new javax.swing.JLabel();
        LabPass2 = new javax.swing.JLabel();
        label_pass1 = new javax.swing.JPasswordField();
        label_pass2 = new javax.swing.JPasswordField();
        LabPass3 = new javax.swing.JLabel();
        check_pass = new javax.swing.JCheckBox();
        label_password = new javax.swing.JLabel();
        label_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_cedula.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        label_cedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        label_email.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        label_email.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        label_nombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        label_nombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        label_apellido.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        label_apellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        LabApellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabApellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabApellido.setText("Apellido:");

        LabNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabNombre.setText("Nombre:");

        LabIdUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabIdUsu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabIdUsu.setText("Id:");

        LabNick.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabNick.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabNick.setText("Nick:");

        LabEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabEmail.setText("E-mail:");

        LabCedula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabCedula.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabCedula.setText("Cédula:");

        label_id.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        label_id.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        label_nick.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        label_nick.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        BotGuardar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        BotGuardar.setText("Guardar");
        BotGuardar.setToolTipText("Guardar los cambios en el perfil");
        BotGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotGuardarActionPerformed(evt);
            }
        });

        BotCancelar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        BotCancelar.setText("Cancelar");
        BotCancelar.setToolTipText("Descartar los cambios y cerrar");
        BotCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotCancelarActionPerformed(evt);
            }
        });

        LabPass1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabPass1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabPass1.setText("Nueva contraseña:");

        LabPass2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabPass2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabPass2.setText("Repetir contraseña:");

        label_pass1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        label_pass2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        LabPass3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabPass3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabPass3.setText("¿Cambiar contraseña?");

        check_pass.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        check_pass.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                check_passStateChanged(evt);
            }
        });

        label_password.setForeground(new java.awt.Color(240, 240, 240));
        label_password.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabNick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabIdUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabCedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_email)
                            .addComponent(label_apellido)
                            .addComponent(label_nombre)
                            .addComponent(label_id, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabPass2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabPass1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabPass3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_pass1)
                            .addComponent(label_pass2)
                            .addComponent(check_pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabIdUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_nick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabNick, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_nombre)
                    .addComponent(LabNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_apellido)
                    .addComponent(LabApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_cedula)
                    .addComponent(LabCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_email)
                    .addComponent(LabEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabPass3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_pass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_pass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_pass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotGuardar)
                    .addComponent(BotCancelar))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 280, 320));

        label_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_titulo.setText("Mi Perfil");
        getContentPane().add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotGuardarActionPerformed
        Boolean error = false;
        
        //VALIDACION DE LOS DATOS DEL FORM
        
        //NOMBRE
        if("".equals(label_nombre.getText())){
            label_nombre.setBackground(Color.pink);
            label_nombre.setToolTipText("Debes completar este campo");
            error = true;
        }else{
            label_nombre.setBackground(Color.white);
            label_cedula.setToolTipText(null);
        }
        //APELLIDO
        if("".equals(label_apellido.getText())){
            label_apellido.setBackground(Color.pink);
            label_apellido.setToolTipText("Debes completar este campo");
            error = true;
        }else{
            label_apellido.setBackground(Color.white);
            label_cedula.setToolTipText(null);
        }
        //CEDULA
        if("".equals(label_cedula.getText())){ //vacio
            label_cedula.setBackground(Color.pink);
            label_cedula.setToolTipText("Debes completar este campo");
            error = true;
        }else if(label_cedula.getText().length() < 8 || label_cedula.getText().length() > 8){ //largo incorrecto
            label_cedula.setBackground(Color.pink);
            label_cedula.setToolTipText("El largo debe ser de 8 cifras, no se admiten puntos ni guiones");
            error = true;
        }else if(!Validador.isNumeric(label_cedula.getText())){ //no numerico
            label_cedula.setBackground(Color.pink);
            label_cedula.setToolTipText("Sólo se admiten números");
            error = true;
        }else{
            int ci = 0; 
            ci =  Integer.parseInt(label_cedula.getText());
            int u = 0;
            u = Validador.validarCedula(ci);
            System.out.println("ci"+u);
            
            if (u == 1){
                label_cedula.setBackground(Color.white);
                label_cedula.setToolTipText("La CI es válida");}
            else{
               label_cedula.setBackground(Color.pink);
               label_cedula.setToolTipText("La CI no es válida. Verifícala.");
               error = true;
            }
        }
        //EMAIL
        if("".equals(label_email.getText())){ //vacio
            label_email.setBackground(Color.pink);
            error = true;
        }else if(!Validador.isEmail(label_email.getText())){ //formato incorrecto
            label_email.setBackground(Color.pink);
            label_email.setToolTipText("El formato de email es incorrecto");
            error = true;
        }else{
            label_email.setBackground(Color.white);
            label_email.setToolTipText(null);
        }
        //CONTRASEÑA
        if(check_pass.isSelected()){    //cambiar contraseña
            if("".equals(label_pass1.getText())){   //pass1 vacía
                label_pass1.setBackground(Color.pink);
                label_pass1.setToolTipText("Debes completar este campo");
                error = true;
            }
            if("".equals(label_pass2.getText())){   //pass2 vacía
                label_pass2.setBackground(Color.pink);
                label_pass2.setToolTipText("Debes completar este campo");
                error = true;
            }
            if(!(label_pass1.getText()).equals(label_pass2.getText())){ //pass diferentes
                label_pass1.setBackground(Color.pink);
                label_pass1.setToolTipText("Las contraseñas no coinciden");
                label_pass2.setBackground(Color.pink);
                label_pass2.setToolTipText("Las contraseñas no coinciden");
                error = true;
            }else{  //pass iguales
                label_password.setText(label_pass1.getText());
            }
            
        }else{  //no cambiar contraseña
            label_password.setText(Global.passUs);
            label_pass1.setBackground(Color.white);
            label_pass1.setToolTipText(null);
            label_pass2.setBackground(Color.white);
            label_pass2.setToolTipText(null);
        }
        
        //GUARDAR CAMBIOS
        if(error == false){
            prc.setVisible(true);
            int resultado = modificarUsuario(label_nombre.getText(), label_apellido.getText(), label_cedula.getText(), label_email.getText(), Global.TipoUs, Global.nickUsLog, label_password.getText(), Integer.parseInt(label_id.getText()));
            prc.dispose();
            
            if(resultado == 0){
                JOptionPane.showMessageDialog(this, "Perfil modificado con éxito.");
                this.dispose();
                Global.passUs = label_password.getText();
            }else if(resultado == -2){
                JOptionPane.showMessageDialog(this, "No se pudieron guardar los cambios.\nNo existe el usuario con el ID: " + Global.IDUsu);
            }else{
                JOptionPane.showMessageDialog(this, "No se pudieron guardar los cambios.\nInténtalo de nuevo");
            }
            /* -2 no existe el idUsuario, -1 nick ya existe, 0 ok */                      
        }else{
                JOptionPane.showMessageDialog(rootPane, "Debes corregir los errores para guardar los datos.", "Error en el formulario", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BotGuardarActionPerformed

    private void BotCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotCancelarActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(rootPane, "¿Cerrar ventana de modificación?\nSe perderá cualquier cambio no guardado.") == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_BotCancelarActionPerformed

    private void check_passStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_check_passStateChanged
        // TODO add your handling code here:
        if(check_pass.isSelected()){ //cambiar contraseña
            label_pass1.setEnabled(true);
            label_pass2.setEnabled(true);
            LabPass1.setEnabled(true);
            LabPass2.setEnabled(true);
        }else{  //no cambiar contraseña
            label_pass1.setEnabled(false);
            label_pass2.setEnabled(false);
            LabPass1.setEnabled(false);
            LabPass2.setEnabled(false);
        }
    }//GEN-LAST:event_check_passStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotCancelar;
    private javax.swing.JButton BotGuardar;
    private javax.swing.JLabel LabApellido;
    private javax.swing.JLabel LabCedula;
    private javax.swing.JLabel LabEmail;
    private javax.swing.JLabel LabIdUsu;
    private javax.swing.JLabel LabNick;
    private javax.swing.JLabel LabNombre;
    private javax.swing.JLabel LabPass1;
    private javax.swing.JLabel LabPass2;
    private javax.swing.JLabel LabPass3;
    private javax.swing.JCheckBox check_pass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField label_apellido;
    private javax.swing.JTextField label_cedula;
    private javax.swing.JTextField label_email;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_nick;
    private javax.swing.JTextField label_nombre;
    private javax.swing.JPasswordField label_pass1;
    private javax.swing.JPasswordField label_pass2;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_titulo;
    // End of variables declaration//GEN-END:variables

    private static String getDataUsuario(java.lang.String nick) {
        _109._2._0._10.server_php.Comision service = new _109._2._0._10.server_php.Comision();
        _109._2._0._10.server_php.ComisionPortType port = service.getComisionPort();
        return port.getDataUsuario(nick);
    }
    
    private static int modificarUsuario(java.lang.String nombre, java.lang.String apellido, java.lang.String cedula, java.lang.String email, int tipoUs, java.lang.String nick, java.lang.String pass, int idUsuario) {
        _109._2._0._10.server_php.Comision service = new _109._2._0._10.server_php.Comision();
        _109._2._0._10.server_php.ComisionPortType port = service.getComisionPort();
        return port.modificarUsuario(nombre, apellido, cedula, email, tipoUs, nick, pass, idUsuario);
    }        
    
    /**
     * Consulta los datos del usuario logueado y muestra los mismos en el form de "Mi Perfil"
     */
    public void CargarDatosUsuario(){
        //consultar datos de usuario y mostrar en formulario
        int c = 0;
        String x = null;
        
        if(Global.nickUsLog != null){
            String datos_usuario = getDataUsuario(Global.nickUsLog);
            String[] dato = datos_usuario.split("=>");

            for (int r=0; r<dato.length; r++){
                x = dato[r];
                c++;
                if(c == 1) {
                    label_nombre.setText(x);
                }
                else{
                    if (c == 2) {
                        label_apellido.setText(x);
                    }
                    else{
                        if ( c == 3 ) {
                            label_cedula.setText(x);
                        }
                        else{
                            if ( c == 4 ) {
                                label_email.setText(x);
                            }
                            else{
                                if (c == 6) {
                                    label_nick.setText(x);
                                }
                                else{
                                    if( c == 8 ){
                                        label_id.setText(x);
                                        idUsu = Integer.parseInt(x);
                                    }
                                }
                            }
                        }
                    }
                }
            }   
            datos_usuario = null;
        }
        prc.dispose();
    }
}
