/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import proyecto.clases.Global;

/**
 *
 * @author SysAdmin
 */
public class ZonaInteresOb extends javax.swing.JFrame {
    private DefaultListModel modelListaObras = new DefaultListModel();
    boolean vacio = false;
    ProcesandoPeticion prc = new ProcesandoPeticion();
    
//    static {
//        if (!vtkNativeLibrary.LoadAllNativeLibraries()) {
//            for (vtkNativeLibrary lib : vtkNativeLibrary.values()) {
//                if (!lib.IsLoaded()) {
//                    System.out.println(lib.GetLibraryName() + " not loaded");
//                }
//            }
//        }
//        vtkNativeLibrary.DisableOutputWindow(null);
//    }
    
    /**
     * Creates new form ZonaInteresOb
     */
    public ZonaInteresOb() {
        Image ico = new ImageIcon(Global.directorioLocal + "\\museo.png").getImage();
        setIconImage(ico);
        initComponents();
        prc.setLocationRelativeTo(null);
        prc.setVisible(true);
        this.setLocationRelativeTo(null);
        ListaObras.setModel(modelListaObras);
        CargarLista();
        prc.dispose();
    }

    public ZonaInteresOb(String titulo) {
        Image ico = new ImageIcon(Global.directorioLocal + "\\museo.png").getImage();
        setIconImage(ico);
        initComponents();
        prc.setLocationRelativeTo(null);
        prc.setVisible(true);
        this.setLocationRelativeTo(null);
        lbl_titulo.setText(titulo + " (2 de 3)");
        this.setTitle(titulo);
        ListaObras.setModel(modelListaObras);
        CargarLista();
        prc.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaObras = new javax.swing.JList();
        BotCancelar = new javax.swing.JButton();
        BotContinuar = new javax.swing.JButton();
        BotAtras = new javax.swing.JButton();
        lbl_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zona de Interés");
        setAlwaysOnTop(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("2- Seleccione una Obra:");

        ListaObras.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ListaObras.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        ListaObras.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaObrasValueChanged(evt);
            }
        });
        ListaObras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ListaObrasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(ListaObras);

        BotCancelar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        BotCancelar.setText("Cancelar");
        BotCancelar.setToolTipText("Cerrar la ventana actual");
        BotCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotCancelarActionPerformed(evt);
            }
        });

        BotContinuar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        BotContinuar.setText("Continuar >>");
        BotContinuar.setToolTipText("Continuar a la siguiente ventana");
        BotContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotContinuarActionPerformed(evt);
            }
        });

        BotAtras.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        BotAtras.setText("<< Atrás");
        BotAtras.setToolTipText("Volver a la selección de Sala");
        BotAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotAtrasActionPerformed(evt);
            }
        });

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_titulo.setText("Agregar Zona de Interés (2 de 3)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotContinuar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotCancelar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotCancelar)
                    .addComponent(BotContinuar)
                    .addComponent(BotAtras))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaObrasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaObrasValueChanged
        // TODO add your handling code here:
        Global.nomObra = (String) ListaObras.getSelectedValue();
    }//GEN-LAST:event_ListaObrasValueChanged

    private void BotCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotCancelarActionPerformed
        // TODO add your handling code here:
        Global.zag = false;
        Global.zelim = false;
        Global.zmod = false;
        Global.IdSala = 0;
        this.setVisible(false);
    }//GEN-LAST:event_BotCancelarActionPerformed

    private void BotAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotAtrasActionPerformed
        // TODO add your handling code here:
        Global.IdSala = 0;
        ZonaInteresSal zis = new ZonaInteresSal(this.getTitle());
        zis.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotAtrasActionPerformed

    private void BotContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotContinuarActionPerformed
        // TODO add your handling code here:
        if(ListaObras.isSelectionEmpty() == true) {
            JOptionPane.showMessageDialog(rootPane, "Debes seleccionar una Obra para continuar."); 
        }else{
            Global.texto = false;
            Global.audio = false;
            Global.video = false;
            Global.modelo3D = false;
            Global.imagen = false;
            
            if(Global.zag == true){ //agregar una zona de interes
                Global.nomObra = (String) ListaObras.getSelectedValue();
                Global.zii = new ZonaInteresIma("agregar");
                Global.zii.setVisible(true);
                Global.zii.setLocationRelativeTo(null);            
            }else{
                if(Global.zelim == true){ //eliminar una zona de interes
                    Global.nomObra = (String) ListaObras.getSelectedValue();
                    elimZi ezi = new elimZi();
                    ezi.setVisible(true);
                }else{ //modificar una zona de interes
                    if(Global.zmod == true){
                        Global.nomObra = (String) ListaObras.getSelectedValue();
                        Global.mzi = new modZi();
                        Global.mzi.setVisible(true);
                    }
                }
            }
            this.setVisible(false);
        }
    }//GEN-LAST:event_BotContinuarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        if(vacio == true){  //cierra la ventana si la Sala no tiene Obras
            ZonaInteresSal ziSal = new ZonaInteresSal(this.getTitle());
            ziSal.setVisible(true);
            this.dispose();
            Global.IdSala = 0;
        }
    }//GEN-LAST:event_formComponentShown

    private void ListaObrasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ListaObrasKeyPressed
        // TODO add your handling code here:
             int k =evt.getKeyCode();
        if(k == KeyEvent.VK_ENTER){

        BotContinuarActionPerformed(null);
        }
    }//GEN-LAST:event_ListaObrasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZonaInteresOb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZonaInteresOb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZonaInteresOb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZonaInteresOb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZonaInteresOb().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotAtras;
    private javax.swing.JButton BotCancelar;
    private javax.swing.JButton BotContinuar;
    private javax.swing.JList ListaObras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables

    private static String getObraSala(int id) {
        _109._2._0._10.server_php.Comision service = new _109._2._0._10.server_php.Comision();
        _109._2._0._10.server_php.ComisionPortType port = service.getComisionPort();
        return port.getObraSala(id);
    }
    
    private void CargarLista(){
        String data = getObraSala(Global.IdSala);
        String[] sep = data.split("=>");
        String e = null;
        
        for (int i=0; i<sep.length; i++){
            e = sep[i];
            
            if("".equals(e)){
                modelListaObras.addElement("< Lista vacía >");
                prc.dispose();
                JOptionPane.showMessageDialog(rootPane, "La Sala seleccionada no tiene Obras asociadas", "Sala vacía", 1);
                vacio = true;
            }else{
                modelListaObras.addElement(e);
                prc.dispose();
                vacio = false;
            }
        }
    }
}
