# Makefile for Curve library
# Created by AE @ ICST 14-11-90
#

EXEDIR  = exe

all:
	(cd $(EXEDIR) ; make -f Makefile CC="$(CC)" CFLAGS="$(CFLAGS)" OTHERLIB="$(OTHERLIB)")

clean:
	(cd $(EXEDIR) ; make -f Makefile clean)

superclean:
	(cd $(EXEDIR) ; make -f Makefile superclean)

ultraclean:
	(cd $(EXEDIR) ; make -f Makefile ultraclean)
